### ISSUE TITLE
small Issues

### ISSUE THREAD

**Issue by cyberkhalil** [khalil2535/UcasGrades#3]
small TO DO missions :- 
- make cache folder hidden.
- if the user cancelled user name or password request show thank message and quit the program.
- change name for cache **file** maybe to Login.data or something like that
- write the user name (UCAS ID) in line and the password (encrypted using same id) in other line on the Login cache file.

**Comment by raduandrone** [comment]
Hi, do you mind if I have a look at this?

**Comment by cyberkhalil** [comment]
Hi @raduandrone , sorry but you can't test this program without being a student in UCAS (university college for applied science) so you can say this repo is just for UCAS students , thanks for offer and have good coding ^_^

**Comment by cyberkhalil** [comment]
Done ,relative commits : https://github.com/khalil2535/UcasGrades/commit/7a7af808783007a6fa8f60b2c01fd3073d231d18 , https://github.com/khalil2535/UcasGrades/commit/ac1d57d75e2227cee2f855452c6098453831f49c & https://github.com/khalil2535/UcasGrades/commit/a3ee807bcb0afa16bb7a47c10362960d0c7ec43c
